// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcExpression.proto

package io.jopen.snack.common.protol;

@Deprecated
public final class DataInfo {
  private DataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransmissionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.jopen.snack.common.protol.Transmission)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getConditionsList();
    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    com.google.protobuf.Any getConditions(int index);
    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    int getConditionsCount();
    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getConditionsOrBuilderList();
    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    com.google.protobuf.AnyOrBuilder getConditionsOrBuilder(
            int index);

    /**
     * <code>.io.jopen.snack.common.protol.Transmission.OperationType operationType = 2;</code>
     * @return The enum numeric value on the wire for operationType.
     */
    int getOperationTypeValue();
    /**
     * <code>.io.jopen.snack.common.protol.Transmission.OperationType operationType = 2;</code>
     * @return The operationType.
     */
    Transmission.OperationType getOperationType();

    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getRowsList();
    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    com.google.protobuf.Any getRows(int index);
    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    int getRowsCount();
    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    com.google.protobuf.AnyOrBuilder getRowsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code io.jopen.snack.common.protol.Transmission}
   */
  public  static final class Transmission extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.jopen.snack.common.protol.Transmission)
      TransmissionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transmission.newBuilder() to construct.
    private Transmission(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transmission() {
      conditions_ = java.util.Collections.emptyList();
      operationType_ = 0;
      rows_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Transmission();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transmission(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                conditions_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000001;
              }
              conditions_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              operationType_ = rawValue;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                rows_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000002;
              }
              rows_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          conditions_ = java.util.Collections.unmodifiableList(conditions_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataInfo.internal_static_io_jopen_snack_common_protol_Transmission_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataInfo.internal_static_io_jopen_snack_common_protol_Transmission_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transmission.class, Builder.class);
    }

    /**
     * Protobuf enum {@code io.jopen.snack.common.protol.Transmission.OperationType}
     */
    public enum OperationType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>QUERY = 0;</code>
       */
      SELECT(0),
      /**
       * <code>UPDATE = 1;</code>
       */
      UPDATE(1),
      /**
       * <code>INSERT = 2;</code>
       */
      INSERT(2),
      /**
       * <code>DELETE = 4;</code>
       */
      DELETE(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>QUERY = 0;</code>
       */
      public static final int SELECT_VALUE = 0;
      /**
       * <code>UPDATE = 1;</code>
       */
      public static final int UPDATE_VALUE = 1;
      /**
       * <code>INSERT = 2;</code>
       */
      public static final int INSERT_VALUE = 2;
      /**
       * <code>DELETE = 4;</code>
       */
      public static final int DELETE_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static OperationType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static OperationType forNumber(int value) {
        switch (value) {
          case 0: return SELECT;
          case 1: return UPDATE;
          case 2: return INSERT;
          case 4: return DELETE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          OperationType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
              public OperationType findValueByNumber(int number) {
                return OperationType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Transmission.getDescriptor().getEnumTypes().get(0);
      }

      private static final OperationType[] VALUES = values();

      public static OperationType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private OperationType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.jopen.snack.common.protol.Transmission.OperationType)
    }

    public static final int CONDITIONS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.Any> conditions_;
    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    public java.util.List<com.google.protobuf.Any> getConditionsList() {
      return conditions_;
    }
    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getConditionsOrBuilderList() {
      return conditions_;
    }
    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    public int getConditionsCount() {
      return conditions_.size();
    }
    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    public com.google.protobuf.Any getConditions(int index) {
      return conditions_.get(index);
    }
    /**
     * <pre>
     * 条件体
     * </pre>
     *
     * <code>repeated .google.protobuf.Any conditions = 1;</code>
     */
    public com.google.protobuf.AnyOrBuilder getConditionsOrBuilder(
        int index) {
      return conditions_.get(index);
    }

    public static final int OPERATIONTYPE_FIELD_NUMBER = 2;
    private int operationType_;
    /**
     * <code>.io.jopen.snack.common.protol.Transmission.OperationType operationType = 2;</code>
     * @return The enum numeric value on the wire for operationType.
     */
    public int getOperationTypeValue() {
      return operationType_;
    }
    /**
     * <code>.io.jopen.snack.common.protol.Transmission.OperationType operationType = 2;</code>
     * @return The operationType.
     */
    public OperationType getOperationType() {
      @SuppressWarnings("deprecation")
      OperationType result = OperationType.valueOf(operationType_);
      return result == null ? OperationType.UNRECOGNIZED : result;
    }

    public static final int ROWS_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.Any> rows_;
    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    public java.util.List<com.google.protobuf.Any> getRowsList() {
      return rows_;
    }
    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    public com.google.protobuf.Any getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <pre>
     * 实体对象
     * </pre>
     *
     * <code>repeated .google.protobuf.Any rows = 5;</code>
     */
    public com.google.protobuf.AnyOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < conditions_.size(); i++) {
        output.writeMessage(1, conditions_.get(i));
      }
      if (operationType_ != OperationType.SELECT.getNumber()) {
        output.writeEnum(2, operationType_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(5, rows_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < conditions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, conditions_.get(i));
      }
      if (operationType_ != OperationType.SELECT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, operationType_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, rows_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Transmission)) {
        return super.equals(obj);
      }
      Transmission other = (Transmission) obj;

      if (!getConditionsList()
          .equals(other.getConditionsList())) return false;
      if (operationType_ != other.operationType_) return false;
      if (!getRowsList()
          .equals(other.getRowsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getConditionsCount() > 0) {
        hash = (37 * hash) + CONDITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getConditionsList().hashCode();
      }
      hash = (37 * hash) + OPERATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + operationType_;
      if (getRowsCount() > 0) {
        hash = (37 * hash) + ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getRowsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Transmission parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transmission parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transmission parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transmission parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transmission parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transmission parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transmission parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transmission parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transmission parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Transmission parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transmission parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transmission parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Transmission prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.jopen.snack.common.protol.Transmission}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.jopen.snack.common.protol.Transmission)
        TransmissionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataInfo.internal_static_io_jopen_snack_common_protol_Transmission_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataInfo.internal_static_io_jopen_snack_common_protol_Transmission_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transmission.class, Builder.class);
      }

      // Construct using io.jopen.snack.common.protol.DataInfo.Transmission.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConditionsFieldBuilder();
          getRowsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (conditionsBuilder_ == null) {
          conditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          conditionsBuilder_.clear();
        }
        operationType_ = 0;

        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataInfo.internal_static_io_jopen_snack_common_protol_Transmission_descriptor;
      }

      @Override
      public Transmission getDefaultInstanceForType() {
        return Transmission.getDefaultInstance();
      }

      @Override
      public Transmission build() {
        Transmission result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Transmission buildPartial() {
        Transmission result = new Transmission(this);
        int from_bitField0_ = bitField0_;
        if (conditionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            conditions_ = java.util.Collections.unmodifiableList(conditions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.conditions_ = conditions_;
        } else {
          result.conditions_ = conditionsBuilder_.build();
        }
        result.operationType_ = operationType_;
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transmission) {
          return mergeFrom((Transmission)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transmission other) {
        if (other == Transmission.getDefaultInstance()) return this;
        if (conditionsBuilder_ == null) {
          if (!other.conditions_.isEmpty()) {
            if (conditions_.isEmpty()) {
              conditions_ = other.conditions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureConditionsIsMutable();
              conditions_.addAll(other.conditions_);
            }
            onChanged();
          }
        } else {
          if (!other.conditions_.isEmpty()) {
            if (conditionsBuilder_.isEmpty()) {
              conditionsBuilder_.dispose();
              conditionsBuilder_ = null;
              conditions_ = other.conditions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              conditionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getConditionsFieldBuilder() : null;
            } else {
              conditionsBuilder_.addAllMessages(other.conditions_);
            }
          }
        }
        if (other.operationType_ != 0) {
          setOperationTypeValue(other.getOperationTypeValue());
        }
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000002);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Transmission parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Transmission) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.Any> conditions_ =
        java.util.Collections.emptyList();
      private void ensureConditionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          conditions_ = new java.util.ArrayList<com.google.protobuf.Any>(conditions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> conditionsBuilder_;

      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public java.util.List<com.google.protobuf.Any> getConditionsList() {
        if (conditionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(conditions_);
        } else {
          return conditionsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public int getConditionsCount() {
        if (conditionsBuilder_ == null) {
          return conditions_.size();
        } else {
          return conditionsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public com.google.protobuf.Any getConditions(int index) {
        if (conditionsBuilder_ == null) {
          return conditions_.get(index);
        } else {
          return conditionsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public Builder setConditions(
          int index, com.google.protobuf.Any value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionsIsMutable();
          conditions_.set(index, value);
          onChanged();
        } else {
          conditionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public Builder setConditions(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.set(index, builderForValue.build());
          onChanged();
        } else {
          conditionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public Builder addConditions(com.google.protobuf.Any value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionsIsMutable();
          conditions_.add(value);
          onChanged();
        } else {
          conditionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public Builder addConditions(
          int index, com.google.protobuf.Any value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionsIsMutable();
          conditions_.add(index, value);
          onChanged();
        } else {
          conditionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public Builder addConditions(
          com.google.protobuf.Any.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.add(builderForValue.build());
          onChanged();
        } else {
          conditionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public Builder addConditions(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.add(index, builderForValue.build());
          onChanged();
        } else {
          conditionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public Builder addAllConditions(
          Iterable<? extends com.google.protobuf.Any> values) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, conditions_);
          onChanged();
        } else {
          conditionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public Builder clearConditions() {
        if (conditionsBuilder_ == null) {
          conditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          conditionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public Builder removeConditions(int index) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.remove(index);
          onChanged();
        } else {
          conditionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public com.google.protobuf.Any.Builder getConditionsBuilder(
          int index) {
        return getConditionsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public com.google.protobuf.AnyOrBuilder getConditionsOrBuilder(
          int index) {
        if (conditionsBuilder_ == null) {
          return conditions_.get(index);  } else {
          return conditionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getConditionsOrBuilderList() {
        if (conditionsBuilder_ != null) {
          return conditionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(conditions_);
        }
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public com.google.protobuf.Any.Builder addConditionsBuilder() {
        return getConditionsFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public com.google.protobuf.Any.Builder addConditionsBuilder(
          int index) {
        return getConditionsFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <pre>
       * 条件体
       * </pre>
       *
       * <code>repeated .google.protobuf.Any conditions = 1;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getConditionsBuilderList() {
        return getConditionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getConditionsFieldBuilder() {
        if (conditionsBuilder_ == null) {
          conditionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  conditions_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          conditions_ = null;
        }
        return conditionsBuilder_;
      }

      private int operationType_ = 0;
      /**
       * <code>.io.jopen.snack.common.protol.Transmission.OperationType operationType = 2;</code>
       * @return The enum numeric value on the wire for operationType.
       */
      public int getOperationTypeValue() {
        return operationType_;
      }
      /**
       * <code>.io.jopen.snack.common.protol.Transmission.OperationType operationType = 2;</code>
       * @param value The enum numeric value on the wire for operationType to set.
       * @return This builder for chaining.
       */
      public Builder setOperationTypeValue(int value) {
        operationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.io.jopen.snack.common.protol.Transmission.OperationType operationType = 2;</code>
       * @return The operationType.
       */
      public OperationType getOperationType() {
        @SuppressWarnings("deprecation")
        OperationType result = OperationType.valueOf(operationType_);
        return result == null ? OperationType.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.jopen.snack.common.protol.Transmission.OperationType operationType = 2;</code>
       * @param value The operationType to set.
       * @return This builder for chaining.
       */
      public Builder setOperationType(OperationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        operationType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.jopen.snack.common.protol.Transmission.OperationType operationType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperationType() {
        
        operationType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          rows_ = new java.util.ArrayList<com.google.protobuf.Any>(rows_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> rowsBuilder_;

      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public java.util.List<com.google.protobuf.Any> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public com.google.protobuf.Any getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public Builder setRows(
          int index, com.google.protobuf.Any value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public Builder setRows(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public Builder addRows(com.google.protobuf.Any value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public Builder addRows(
          int index, com.google.protobuf.Any value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public Builder addRows(
          com.google.protobuf.Any.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public Builder addRows(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public Builder addAllRows(
          Iterable<? extends com.google.protobuf.Any> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public com.google.protobuf.Any.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public com.google.protobuf.AnyOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public com.google.protobuf.Any.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public com.google.protobuf.Any.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <pre>
       * 实体对象
       * </pre>
       *
       * <code>repeated .google.protobuf.Any rows = 5;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.jopen.snack.common.protol.Transmission)
    }

    // @@protoc_insertion_point(class_scope:io.jopen.snack.common.protol.Transmission)
    private static final Transmission DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Transmission();
    }

    public static Transmission getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transmission>
        PARSER = new com.google.protobuf.AbstractParser<Transmission>() {
      @Override
      public Transmission parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transmission(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transmission> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Transmission> getParserForType() {
      return PARSER;
    }

    @Override
    public Transmission getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_jopen_snack_common_protol_Transmission_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_jopen_snack_common_protol_Transmission_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023rpcExpression.proto\022\034io.jopen.snack.co" +
      "mmon.protol\032\022protobuf/any.proto\"\356\001\n\014Tran" +
      "smission\022(\n\nconditions\030\001 \003(\0132\024.google.pr" +
      "otobuf.Any\022O\n\roperationType\030\002 \001(\01628.io.j" +
      "open.snack.common.protol.Transmission.Op" +
      "erationType\022\"\n\004rows\030\005 \003(\0132\024.google.proto" +
      "buf.Any\"?\n\rOperationType\022\n\n\006SELECT\020\000\022\n\n\006" +
      "UPDATE\020\001\022\n\n\006INSERT\020\002\022\n\n\006DELETE\020\004B\nB\010Data" +
      "Infob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_io_jopen_snack_common_protol_Transmission_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_jopen_snack_common_protol_Transmission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_jopen_snack_common_protol_Transmission_descriptor,
        new String[] { "Conditions", "OperationType", "Rows", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
