server:
  port: 8090
  servlet:
    context-path: /


spring:
  mvc:
    throw-exception-if-no-handler-found: true

  redis:
    database: 0
    host: 192.168.0.109
    lettuce:
      pool:
        max-active: 200   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 0     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    port: 6379



#上传的上线次数
uploadLimit: 100

#加密配置
encrypt:
  body:
    aes-key: KlF2PoLgMCIJsvyh #AES加密秘钥
    des-key: KLMf9Jz3Puv7TTxi #DES加密秘钥
